-- Generated by nwg-displays on 2026-09-10 at 12:11:43. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@180.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
