###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = pgrep -x wofi > /dev/null && pkill -x wofi || wofi --show drun
$menu_logout = pkill wlogout || wlogout -b 2 -c 10 -r 10
$taskmanager = flatpak kill net.nokyan.Resources || net.nokyan.Resources

$mainMod = SUPER # Sets "Windows" key as main modifier
