
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
windowrule {
    name = hyprquickframe-setup

    match:class = hyprquickframe

    float = yes
    center = yes
    pin = yes
}

windowrule {
    name = gwenview-float
    match:class = org.kde.gwenview
    float = yes
    center = yes
    size = 1200 800
}

windowrule {
    name = veadotube-float
    match:class = veadotube-mini
    float = yes
    center = yes
    size = 800 700
}

windowrule {
    name = Resources-float
    match:class = net.nokyan.Resources
    float = yes
    center = yes
    size = 850 600
}

windowrule {
    name = linux-wallpaperengine-canvas
    match:class = ^linux-wallpaperengine$

    float = true
    size = 100% 100%
    pin = true
    no_focus = true
    focus_on_activate = false
}

windowrule {
    name = hyprland-share-picker-float
    match:class = ^hyprland-share-picker$
    float = true
    center = true
    size = 500 400
}

windowrule {
    name = obs-projector-workspace10
    match:class = ^com\.obsproject\.Studio$
    match:title = ^Projector - Preview$
    workspace = 10 silent
}
